// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTCvHqbO9UvoJxVM9jQ_VL9fXGRoqa8MM',
    appId: '1:848454495631:web:e6addca3b33528dea06ffa',
    messagingSenderId: '848454495631',
    projectId: 'flutter-firebase-auth-exercise',
    authDomain: 'flutter-firebase-auth-exercise.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-exercise.firebasestorage.app',
    measurementId: 'G-5XSYD3JB96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMPb39mT5bLWNX1_ZXkrTbDtpiBI4HzUo',
    appId: '1:848454495631:android:dbba13dcf1b528c5a06ffa',
    messagingSenderId: '848454495631',
    projectId: 'flutter-firebase-auth-exercise',
    storageBucket: 'flutter-firebase-auth-exercise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_8Csn9BeKmsW--LklrqIp9alkUPGwAr8',
    appId: '1:848454495631:ios:e78f56e666e1ff58a06ffa',
    messagingSenderId: '848454495631',
    projectId: 'flutter-firebase-auth-exercise',
    storageBucket: 'flutter-firebase-auth-exercise.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuthComplete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_8Csn9BeKmsW--LklrqIp9alkUPGwAr8',
    appId: '1:848454495631:ios:e78f56e666e1ff58a06ffa',
    messagingSenderId: '848454495631',
    projectId: 'flutter-firebase-auth-exercise',
    storageBucket: 'flutter-firebase-auth-exercise.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuthComplete',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTCvHqbO9UvoJxVM9jQ_VL9fXGRoqa8MM',
    appId: '1:848454495631:web:3277c1f7b8b8bdcea06ffa',
    messagingSenderId: '848454495631',
    projectId: 'flutter-firebase-auth-exercise',
    authDomain: 'flutter-firebase-auth-exercise.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-exercise.firebasestorage.app',
    measurementId: 'G-ZFJ2D5TW0W',
  );
}
